app/src/main/res/layout/activity_manga_reader.xml
Double tap zoom is currently rather high, lowering it to be 33% of maximum zoom as opposed to 50% 
[See Discord Suggestion](https://discord.com/channels/1163949787213746248/1165496150233718884/1168448587542298716)
=> making double tap zoom lower in manga reader

app/src/main/java/ani/dantotsu/media/anime/SelectorDialogFragment.kt
Forgive me if it's bad practice to create a second pr, I wasn't sure on how to remove the unnecessary commit from the original one
Previously, if the video was zero megabytes, it would show "0 MB", I've changed this to now show "Unknown Size".
See [Issue 8](https://github.com/rebelonion/Dantotsu/issues/8)
=> when video size is 0mb, display unknown size instead

app/src/main/java/ani/dantotsu/media/manga/MangaReadFragment.kt
Mainly updates the context receiver line of code to adhere to the API 34 guidelines, by adding Context.RECEIVER_NOT_EXPORTED: https://developer.android.com/about/versions/14/behavior-changes-14
=> Updated Support For Android 14 (API 34) (WIP)

app/src/main/java/ani/dantotsu/media/anime/AnimeWatchFragment.kt
use episode titles from kitsu if kitsu doesn't have episode titles use episode titles from anime source
all the sources except aniwave, aniwatch, kaido, doesn't provide episode titles so using the episode titles from kitsu would be great
you can also try this artifact build and test it yourself
https://github.com/Yutatsu0/Dantotsu/actions/runs/7595023003/artifacts/1183041478
=> use episode titles from kitsu

app/src/main/java/ani/dantotsu/media/MediaInfoFragment.kt, app/src/main/res/layout/fragment_media_info.xml
currently the average duration is in minutes so now
if it's like minutes for example 24 mins
if it's like hour and minutes for example 1 hour, 53 mins
if it's more than one hour and minutes for example 2 hours, 14 mins
here are some screenshots comparison
before
after
=> added episode duration formatting

app/src/main/java/ani/dantotsu/connections/discord/RPC.kt, app/src/main/java/ani/dantotsu/settings/SettingsActivity.kt, app/src/main/java/ani/dantotsu/settings/saving/Preferences.kt, app/src/main/res/anim/bounce_zoom.xml, app/src/main/res/drawable/discord_status_dnd.xml, app/src/main/res/drawable/discord_status_idle.xml, app/src/main/res/drawable/discord_status_online.xml, app/src/main/res/layout/activity_settings.xml
- changes the discord status in the rich presence
- selection between online, idle or dnd for discord
- only viewable for users that are logged in discord
**Note:**
The discord client status overrides the rich presence status.
→ This means that if you have discord opened it will use the status of your discord client and not the status of set by dantotsu. This is set by discord and not possible to bypass. The status set by dantotsu will not get overridden if discord is closed on every logged in device.
=> Discord Status Switcher

app/src/google/java/ani/dantotsu/others/AppUpdater.kt
The download manager actually takes care of the heavy lifting. It returns null in the case of an unsuccessful download.
=> fix: optimize querying download uri

app/src/main/java/ani/dantotsu/Functions.kt, app/src/main/java/ani/dantotsu/MainActivity.kt, app/src/main/java/ani/dantotsu/media/manga/MangaReadFragment.kt, app/src/main/java/ani/dantotsu/media/manga/mangareader/MangaReaderActivity.kt, app/src/main/java/ani/dantotsu/settings/DevelopersDialogFragment.kt, app/src/main/res/values/themes.xml
When I submitted the previous PR to hide the navigation bar on the main screen, I hadn't noticed the hidden attempt to do it using now deprecated methods. While the methods were still working for quite a long time after being deprecated, parts became obsolete in one of the last two or three Android versions.
This fixes a bunch of dead code with more future-poof methods.
This also adds the same conversions for right to left to the bottom to top. It doesn't fix the paged scrolling inversion, but sets everything else the way it needs to be for when that is resolved.
=> Cleaning up navigation

app/src/main/java/ani/dantotsu/Functions.kt, app/src/main/java/ani/dantotsu/media/anime/AnimeWatchFragment.kt, app/src/main/java/ani/dantotsu/media/manga/MangaReadFragment.kt, app/src/main/java/ani/dantotsu/themes/ThemeManager.kt
This one is pretty straightforward. Sets the navbar themes whereever activities are initialized. Also fixes setting it on both the manga AND anime chapter / episode lists, while leaving the main view with a transparent one.
=> fix: reapply theme to each init call

app/src/main/java/ani/dantotsu/Functions.kt, app/src/main/java/ani/dantotsu/MainActivity.kt, app/src/main/java/ani/dantotsu/media/manga/mangareader/MangaReaderActivity.kt
Hiding the bars seems to work great, but things get a little awkward when they aren't hidden or get hidden later. The two most notable issues this is meant to address are the chapter names getting jammed behind the status bar and the app's nav bar falling behind the system nav bar while there is a giant gap at the top.
<details>
<summary>Bars shown</summary>
</details>
<details>
<summary>Bars hidden</summary>
</details>
=> feat: add an option to revert bar hide

app/src/main/java/ani/dantotsu/MainActivity.kt
It functions a lot like onResume, but assumes that onCreate ran and the user navigated away from the activity completely.
This eliminates some of the overlap between onCreate, onAttachedToWindow (doOnAttach), and returning from another activity where the views are created, but the navbar color was overwritten.
=> fix: forgotten uncle onRestart

app/src/main/java/ani/dantotsu/media/anime/SelectorDialogFragment.kt, app/src/main/res/values/strings.xml
The current design simply presents an empty server list and leaves the user to click away. No action can be taken without leaving the dialog.
=> fix: error when streams are empty

app/src/main/java/ani/dantotsu/MainActivity.kt
Portrait compensates for system navigation, which bleeds into landscape (where system nav is on the side) and places the bar 1/3 into the screen.
=> fix: remove landscape buffer

app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
If using the option to hide the skip button after a delay, setting 0 results in a generic +85 button with no click action.
=> fix: hide the skip button if hidden

app/build.gradle
This is separate from lint because updating libraries can have unintended side effects that need to be addressed.
For some reason, gradle hates the array of manifest subs. They want dynamic properties or individual references. The individual references are a bit less tedious to track with only two parameters.
=> fix: update gradle dependancies

app/src/main/java/ani/dantotsu/connections/anilist/AnilistQueries.kt, app/src/main/java/ani/dantotsu/media/MediaListDialogFragment.kt, app/src/main/java/ani/dantotsu/media/MediaListDialogSmallFragment.kt, app/src/main/res/values/strings.xml
This was split off from #245 because it's useful with or without the other feature. 
When you add an item to a list on the home screen, you can long click to open the list editor. Unfortunately, the delete button is tied to an id that is only available after opening the item and using the list editor in that view. 
This adds fallback for retrieving an id that will allow deleting from the home screen. The query is limited to the media list entry, which may be useful for something else in the future.
=> feat: delete item from context menu

app/src/main/java/ani/dantotsu/Functions.kt, app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt, app/src/main/java/ani/dantotsu/others/Xpandable.kt, app/src/main/java/ani/dantotsu/settings/PlayerSettingsActivity.kt, app/src/main/java/ani/dantotsu/settings/SettingsActivity.kt, app/src/main/java/ani/dantotsu/settings/UserInterfaceSettingsActivity.kt, app/src/main/java/ani/dantotsu/settings/saving/Preferences.kt, app/src/main/res/layout/activity_player_settings.xml, app/src/main/res/values/strings.xml
This adds a transparency setting along with an early version of a subtitle preview. In addition, the backend to doing this updates the restart and refresh actions as shared calls, adds a state listener to the custom expandable view, and (somehow) inherited a few string fixes meant to be part of a previous PR.
=> Add transparency options to subtitle

app/src/main/java/ani/dantotsu/Functions.kt
While caching the original and the final seems like an ideal way to reduce overhead, you cache an original copy of the image and the modified copy of the image to only ever load the modified copy. The size is set, meaning you are not reusing the original image. There is no reason to cache it.
=> fix: prefer caching the final version

app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt, app/src/main/java/ani/dantotsu/media/anime/SelectorDialogFragment.kt, app/src/main/java/ani/dantotsu/parsers/AniyomiAdapter.kt
A very basic and somewhat cheesy way to offload torrent streaming to an app that supports it. Credit to kuukiyomi for the name of the app and providing the extras that can be targeted. Doesn't seem to return the intent well to actually support proper tracking updates, but it is a temporary solution.
=> feat: support exporting magnets

app/src/main/java/ani/dantotsu/Functions.kt, app/src/main/java/ani/dantotsu/media/MediaDetailsActivity.kt, app/src/main/java/ani/dantotsu/media/comments/CommentsFragment.kt, app/src/main/java/ani/dantotsu/profile/ProfileActivity.kt, app/src/main/java/ani/dantotsu/profile/ProfileFragment.kt, app/src/main/java/ani/dantotsu/profile/StatsFragment.kt, app/src/main/java/ani/dantotsu/profile/activity/FeedFragment.kt, app/src/main/res/layout/activity_profile.xml, app/src/main/res/layout/fragment_comments.xml, app/src/main/res/layout/fragment_profile.xml
@sneazy-ibo @aayush2622 Gather round and let me tell you a story....
`WindowCompat.setDecorFitsSystemWindows(window, false)` disables the limits placed on a window by the status bar and system navigation. It's set in the app to deal with the status bar, but then all of the views are compensating in code for the navigation bar that is still being shown. This leaves you constantly accounting for the system navigation when it's shown.
The AnimatedBottomBar is a library that draws its own view. If you set the size of it, it will pretty much ignore that and draw the same size as it would have from top to bottom, either being cut off or leaving a gap. If the size is taller than the view it draws, there will be a transparent gap at the bottom. So if you can't set the height, how do you avoid …
=> fix: add padding to last item in recycler

app/src/main/java/ani/dantotsu/media/MediaInfoFragment.kt, app/src/main/java/ani/dantotsu/media/SearchActivity.kt, app/src/main/res/layout/fragment_media_info.xml, app/src/main/res/layout/item_quels.xml, app/src/main/res/layout/item_title_search.xml, app/src/main/res/values/strings.xml
This is a compromise between systematically tracing a season in both directions to find all prequels / sequels and scraping third-party sources in https://github.com/rebelonion/Dantotsu/issues/301 using search. It even keeps things pretty by presenting it as an actual search, rather than simply performing the query directly
=> feat: add watch title search button

app/src/main/java/ani/dantotsu/Functions.kt, app/src/main/java/ani/dantotsu/media/manga/mangareader/BaseImageAdapter.kt, app/src/main/java/ani/dantotsu/media/manga/mangareader/MangaReaderActivity.kt
Fixes navigating to the wrong chapter, despite the UI being correct. Makes bottom to top its own setting that functions as expected, not just top to bottom with a RTL slider bar.
This is one I started a while back and then didn't have the patience to unravel at the time.
=> fix: make bottom to top work properly

app/src/main/java/ani/dantotsu/Functions.kt, app/src/main/java/ani/dantotsu/connections/bakaupdates/MangaUpdates.kt
The API is somewhat broken. If the latest chapter were ever filled, that would be awesome. Then you have random volumes showing up as the first result, but they are 100 chapters behind. In one case, the chapter number was a float. Basically, that leaves you wanting an item that has a release date filled in and either has a value that pretty much never exists or at least is a chapter not part of volume.
=> fix: fix the fix for MangaUpdates

app/src/main/java/ani/dantotsu/settings/ExtensionsActivity.kt, app/src/main/java/ani/dantotsu/settings/SettingsActivity.kt, app/src/main/res/layout/activity_extensions.xml, app/src/main/res/layout/dialog_repositories.xml, app/src/main/res/values/strings.xml
didn't really account for an accidental press with an empty entry and I don't think we need to clear the user agent
=> feat: repo editor in extension window

app/src/main/java/ani/dantotsu/parsers/AniyomiAdapter.kt
Removes hard-coded array access (that can crash) for logs that are no longer needed.
=> fix: remove unneeded (& problematic) logs

app/src/main/java/ani/dantotsu/media/Media.kt, app/src/main/java/ani/dantotsu/media/MediaListDialogFragment.kt, app/src/main/java/ani/dantotsu/media/MediaListDialogSmallFragment.kt
Rather than dismissing and removing all of the state for the queries before even confirming that they've finished (interesting idea @rebelonion), the dismissal only happens upon success.
=> fix: deletion queries
