rebelonion/Dantotsu

- app/src/main/java/ani/dantotsu/home/AnimePageAdapter.kt
- app/src/main/java/ani/dantotsu/home/HomeFragment.kt
- app/src/main/java/ani/dantotsu/home/MangaPageAdapter.kt
- app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
- app/src/main/java/ani/dantotsu/media/manga/mangareader/MangaReaderActivity.kt
- app/src/main/java/ani/dantotsu/media/user/ListActivity.kt
- app/src/main/java/ani/dantotsu/settings/PlayerSettingsActivity.kt
- app/src/main/java/ani/dantotsu/settings/SettingsActivity.kt
- app/src/main/java/ani/dantotsu/settings/SettingsDialogFragment.kt
- app/src/main/java/ani/dantotsu/settings/UserInterfaceSettings.kt
- app/src/main/java/ani/dantotsu/settings/UserInterfaceSettingsActivity.kt
- app/src/main/res/drawable/ic_round_delete_24.xml
- app/src/main/res/layout/activity_list.xml
- app/src/main/res/layout/activity_user_interface_settings.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/item_anime_page.xml
- app/src/main/res/layout/item_anime_watch.xml
- app/src/main/res/layout/item_chapter_list.xml
- app/src/main/res/layout/item_custom_dialog.xml
- app/src/main/res/layout/item_manga_page.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/style.xml
1.15x speed
better manga title/list name view
> some changes

- app/src/main/res/layout/activity_user_interface_settings.xml
> Added mismatched switch

- app/src/main/java/ani/dantotsu/media/anime/AnimeNameAdapter.kt
- app/src/main/java/ani/dantotsu/media/anime/AnimeWatchAdapter.kt
- app/src/main/java/ani/dantotsu/media/anime/EpisodeAdapters.kt
- app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
- app/src/main/java/ani/dantotsu/media/manga/MangaNameAdapter.kt
Remove episode number from episode title using Regex
make the episode title look like in saikou does
> Remove episode number from episode title like saikou

- app/src/main/java/ani/dantotsu/MainActivity.kt
- app/src/main/java/ani/dantotsu/offline/OfflineFragment.kt
If offline mode is on and you restart app it will still take you to offline mode
> fixed offline mode

- app/src/main/java/ani/dantotsu/media/anime/EpisodeAdapters.kt
- app/src/main/java/ani/dantotsu/media/manga/MangaChapterAdapter.kt
* warning menu when deleting episode
* auto hide desc if ep is downloaded(looked very bad when both was visible)
> warning menu when deleting episode

- app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
sometimes the video starts buffering so I added 10 minutes ahead buffer, and also 2 minutes back buffer so the video won't have to reload when rewinding
> added default load control

- app/src/main/java/ani/dantotsu/media/manga/MangaReadAdapter.kt
- app/src/main/res/drawable/invert_all_boxes.xml
- app/src/main/res/drawable/tick_all_boxes.xml
- app/src/main/res/drawable/untick_all_boxes.xml
- app/src/main/res/layout/custom_dialog_layout.xml
- Toggle button is overlaying scroll view without impacting the layout
- Image switcher for three different states
- tick
- untick
- invert
- all boxes ticked → untick all boxes
- all boxes unticked → tick all boxes
- not all boxes ticked/unticked → invert selection
> feat: scanlation bulk ticker

- app/src/main/java/ani/dantotsu/home/HomeFragment.kt
- app/src/main/java/ani/dantotsu/settings/SettingsDialogFragment.kt
- app/src/main/res/layout/item_notification.xml
The linear nav gradient fucked in light mode btw 😔
> feat: fixed the UI changes 🦍 + notificationIcon logic and long press userAvatar 🐒

- app/src/main/java/ani/dantotsu/media/manga/mangareader/MangaReaderActivity.kt
This was actually driving me nuts because I kept hitting the wrong button.
> fix: swap chapter names and nav on RTL

- app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
* feat (player): added portrait mode to exoplayer video player
> feat (player): added portrait mode

- app/src/main/java/ani/dantotsu/download/anime/AnimeDownloaderService.kt
- app/src/main/java/ani/dantotsu/download/manga/MangaDownloaderService.kt
- app/src/main/java/ani/dantotsu/download/novel/NovelDownloaderService.kt
- app/src/main/java/ani/dantotsu/util/Logger.kt
Build.RADIO has been deprecated since API 15, which means it hasn't worked since before the lowest target API of the app, and versioncode is deprecated in API 28.
> fix: address deprecated code

- app/build.gradle
- app/src/main/java/ani/dantotsu/Functions.kt
- app/src/main/java/ani/dantotsu/MainActivity.kt
- app/src/main/java/ani/dantotsu/download/anime/AnimeDownloaderService.kt
- app/src/main/java/ani/dantotsu/media/novel/NovelResponseAdapter.kt
- app/src/main/java/ani/dantotsu/profile/ProfileFragment.kt
- app/src/main/java/eu/kanade/tachiyomi/util/system/ContextExtensions.kt
- app/src/main/java/eu/kanade/tachiyomi/util/system/NotificationExtensions.kt
- app/src/main/res/values-v23/themes.xml
- app/src/main/res/values/themes.xml
> feat: support API 21 with compat (WIP)

- app/src/main/java/ani/dantotsu/media/anime/AnimeWatchAdapter.kt
- app/src/main/java/ani/dantotsu/media/manga/MangaReadAdapter.kt
- app/src/main/java/ani/dantotsu/settings/SettingsActivity.kt
- app/src/main/java/ani/dantotsu/settings/saving/Preferences.kt
- app/src/main/res/drawable/ic_round_search_sources_24.xml
- app/src/main/res/layout/activity_settings_common.xml
- app/src/main/res/values/strings.xml
Starting from the previously used source or 0, if this is a new item, this option will keep going down the list through sources until it finds a hit. It will stop at the end of the list. If you want to continue down the list after finding one, simply select the next source and it will continue down. It does not recycle back to the beginning to avoid an infinite loop.
> Automatically search through sources

- app/src/main/java/ani/dantotsu/home/AnimePageAdapter.kt
- app/src/main/java/ani/dantotsu/home/HomeFragment.kt
- app/src/main/java/ani/dantotsu/home/MangaPageAdapter.kt
Please, someone. Anyone. Tell me it's OK to let go....
> feat: add haptics to long click event

- app/src/main/java/ani/dantotsu/home/AnimePageAdapter.kt
- app/src/main/java/ani/dantotsu/home/MangaPageAdapter.kt
- app/src/main/java/ani/dantotsu/settings/UserInterfaceSettingsActivity.kt
- app/src/main/java/ani/dantotsu/settings/saving/Preferences.kt
- app/src/main/res/layout/activity_user_interface_settings.xml
- app/src/main/res/values/strings.xml
> featL option to disable trending scroll

- app/src/main/java/ani/dantotsu/media/SearchActivity.kt
https://github.com/rebelonion/Dantotsu/assets/1173913/ec006b48-e53a-491c-a770-a483ae2406b6
> feat: suppress ime for search in progress

- app/src/main/java/ani/dantotsu/media/manga/mangareader/ChapterLoaderDialog.kt
- app/src/main/res/values/strings.xml
This is just some stuff that breaks immersion
> Manga reader quirks

- app/src/main/res/values/strings.xml
This reverts (some of) commit c29147a6817e01c3d0284b50d4ff428735792681.
> Revert (some of) "Just some quality of life garbage (#304)"

- app/src/main/java/ani/dantotsu/Functions.kt
- app/src/main/java/ani/dantotsu/connections/bakaupdates/MangaUpdates.kt
- app/src/main/java/ani/dantotsu/media/MediaInfoFragment.kt
- app/src/main/java/ani/dantotsu/media/anime/AnimeWatchAdapter.kt
- app/src/main/java/ani/dantotsu/util/CountUpTimer.kt
- app/src/main/res/values/strings.xml
Let's try this again, but rather than trying to get the results we want, let the dumpster fire of a search return whatever and filter out the null values. Somehow, this worked better than actually trying to limit the search, so whatever.
> feat: add a time since chapter item

- .github/workflows/beta.yml
Cleaned up the telegram upload and put the upload with the commit at the bottom because telegram puts the text at the bottom. Also I make it spit out the commit logs for the guy making the obtaimium script.
> Fixed artifact upload

- app/src/main/java/ani/dantotsu/Functions.kt
- app/src/main/java/ani/dantotsu/connections/bakaupdates/MangaUpdates.kt
- app/src/main/res/values/strings.xml
Probably would have saved a lot of elaborate attempts to fix the issue by simply going the other way.
> fix: it was only an int for convenience

- app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
Extracted from the changes for torrents. Appears to fix whatever is going on with https://github.com/rebelonion/Dantotsu/issues/334
> fix: exo / subtitle improvements

- app/src/main/java/ani/dantotsu/util/BitmapUtil.kt
- app/src/main/java/ani/dantotsu/widgets/statistics/ProfileStatsConfigure.kt
- app/src/main/java/ani/dantotsu/widgets/statistics/ProfileStatsWidget.kt
- app/src/main/java/ani/dantotsu/widgets/upcoming/UpcomingRemoteViewsFactory.kt
- app/src/main/java/ani/dantotsu/widgets/upcoming/UpcomingWidget.kt
Figured with all the caching shenanigans in the other one, you may want them all shared or might want to divide what is and isn't into separate sets of preferences.
> feat: add per-widget configuration

- .github/workflows/beta.yml
> Why use decapitated actions?

- .github/workflows/beta.yml
It will fix it in its next build. Dunno what happened to telegram bot tho. It isn't even working on mine.
> Fix commit messages in discord

- app/src/main/java/ani/dantotsu/media/CalendarActivity.kt
- app/src/main/java/ani/dantotsu/media/OtherDetailsViewModel.kt
- app/src/main/java/ani/dantotsu/media/user/ListActivity.kt
- app/src/main/res/drawable/ic_round_library_books_24.xml
- app/src/main/res/layout/activity_list.xml
- app/src/main/res/values/strings.xml
Needs caching to avoid ratelimit through spamming
https://github.com/rebelonion/Dantotsu/assets/41344259/94766c6d-211f-4347-8460-ac33c4d364d1
> feat: showOnlyLibrary button in Calendar

- app/build.gradle
> Fix :fixed the local dev problem with the injekt dependency

- app/src/main/java/ani/dantotsu/media/manga/mangareader/Swipy.kt
Fixed https://discord.com/channels/1163949787213746248/1251412931657072692
This wasn't really going away if tried to make small changes to the code..
The other "fix" that was fixed by rintaro and shivam, though fixed this bug, broke other parts of mangareader. Like you couldn't swipe to the next page if you were on the 1st page of any manga.
I have removed some notes(I don't think are needed) and at least _tried_ to make the code easy to understand. 
This pull doesn't change any other file other than the swipy.kt like the other pull so you can review and merge it.
@dawnusedyeet on discord.
This pr is for dev branch.
> Made swipy same as other fixed branch

- app/src/main/java/ani/dantotsu/media/SubtitleDownloader.kt
> chore: update SubtitleDownloader.kt

- app/src/main/java/ani/dantotsu/media/manga/MangaReadAdapter.kt
- app/src/main/java/ani/dantotsu/settings/saving/PrefManager.kt
> feat:added way to clear saved manga progress

- .github/workflows/beta.yml
I think the hex_to_decimal thing is causing problem I am not sure why are doing that that and not just define the colors in decimal and avoid the problem all together @sneazy-ibo should tell me why is it needed
> Fix: Workflow hopefully

- app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
- app/src/main/java/ani/dantotsu/others/Xubtitle.kt
- app/src/main/java/ani/dantotsu/settings/PlayerSettingsActivity.kt
- app/src/main/java/ani/dantotsu/settings/saving/Preferences.kt
- app/src/main/res/layout/activity_player_settings.xml
- app/src/main/res/layout/exo_player_view.xml
- app/src/main/res/values/strings.xml
> Feat(exoplayer): custom subtitle view

- .github/workflows/beta.yml
there was Someplaces where hex to decimal function was not used previous default color (also changed by me) was out of color range hopefully it is finally fixed
> fix: discord embed

- app/src/main/java/ani/dantotsu/download/manga/MangaDownloaderService.kt
- app/src/main/java/ani/dantotsu/media/manga/MangaReadFragment.kt
Added a check for pages that are not being downloaded, if not downloaded after 25 tries, chapter gets deleted.
> Fixed missing manga pages when downloading

- app/src/main/java/ani/dantotsu/media/manga/MangaReadAdapter.kt
- app/src/main/res/layout/dialog_layout.xml
users can enter the value required to install as there is an EditText field instead of the Text View
> To download multiple mangas
